CREATE DATABASE burgers_db;

CREATE TABLE burgers_db.burgers (
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(50),
	devoured BOOLEAN DEFAULT FALSE,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id));
)